### ISSUE TITLE
How can I change to other arm?

### ISSUE THREAD

**Issue by superggb** [abr/abr_jaco2#21]
Hello!

It's interesting to use ABR to control arm and plan force for I used to ros API. 
However I'm using Mico Arm to do some research, how can I change to my arm?
For example, where can I find RS485API and other config file?

**Comment by p3jawors** [comment]
Hi superbbg and thanks for the interest in the abr_jaco repo. 

This repo has only been tested on the Kinova Jaco^2 6DOF robotic arm, and if your Mico uses the same API you should be able to use our interface with some changes you will need to make on the C side, depending on which Mico arm you have. During the process of getting this going for the Jaco^2 we had a lot of help from kinova, who sent some very useful documentation. I've attached what could be useful, but you will need to get in touch with them for some information. Here are the things that come to mind that you will need to do to get this working with a Mico:

1. If you have the 4DOF Mico, then there will be some variables that need to be updated in `interfaces/jaco2_rs485.h` as they have been setup for 6D length variables for the Jaco2

2. There are some constants that will need to be updated in `interfaces/jaco2_rs485.cpp` that have been hardcoded for the Jaco2. Things like `TORQUE_KP`, `TORQUE_KI`, `TORQUE_KD`, possibly the joint / hand addresses. Check the `default_parameters.pdf` that I've attached. This has a bunch of constants for the jaco2 and mico2. If you have a different Mico you will need to contact Kinova for a similar document
[default_parameters.pdf](https://github.com/abr/abr_jaco2/files/5090465/default_parameters.pdf)

3. Depending on changes in the previous 2 steps, you will need to update the `jaco2_cython.pyx` file to reflect them. This will mainly be for dimensionality of data passed to the arm.

4. You will need to create a new config file for the Mico, like we have done for the jaco in `config/config.py`. This will entail updating: the inertias, lengths, masses, and transforms between links and joints. You will need to get these values from Kinova. We received an excel sheet for the inertia and mass information from Kinova. The lengths I found in some of the common documentation available on their website, which was used to make the transformation matrices. If you have not done this before, I highly recommend @studywolf blog posts on robot control. This is a several part series, which goes over the process we went in deriving our transforms. [Part 1](https://studywolf.wordpress.com/2013/08/21/robot-control-forward-transformation-matrices/) is a good overview, and [this one](https://studywolf.wordpress.com/2017/06/09/deriving-a-robots-transform-matrices/) goes over it in some more detail. I recommend going over at least these two to get you started.

5. For controllers and path planners you will need to install [abr_control](https://github.com/abr/abr_control). There are also other examples of configs there for the ur5 and simple 1 to 3 link arms there.

I've also attached a document going over the RS485 message structure.
[rs485_message_structure.pdf](https://github.com/abr/abr_jaco2/files/5090525/rs485_message_structure.pdf)

Godspeed in your endevour

**Comment by superggb** [comment]
Hi p3jawors.
It's very kind of you to give me such detailed solution. I will try it soon with my best effort.
Thanks a lot !
