### ISSUE TITLE
Can't build setup.py

### ISSUE THREAD

**Issue by taegyuahn** [abr/abr_jaco2#23]
Hi, I'm want to use these library in order to operate real jaco2 arm.

So I cloned these repository and tried to run "python setup.py install" as the installation guide suggests.

but the error message occured as the quote below.

I already installed  "ABR_Control" repo where this "ABR_jaco2" repo depends on
and I even changed the version of the cython to cython==0.29 (at conda env) as the setup.py file requires
but the error message didn't changed.

Could you help me?

> $ python setup.py install
> /home/mlcs/anaconda3/envs/py/lib/python3.7/site-packages/setuptools/dist.py:461: UserWarning: Normalizing '0.1.0.dev' to '0.1.0.dev0'
>   warnings.warn(tmpl.format(**locals()))
> running install
> running bdist_egg
> running egg_info
> writing abr_jaco2.egg-info/PKG-INFO
> writing dependency_links to abr_jaco2.egg-info/dependency_links.txt
> writing requirements to abr_jaco2.egg-info/requires.txt
> writing top-level names to abr_jaco2.egg-info/top_level.txt
> reading manifest file 'abr_jaco2.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> warning: no files found matching '*.dll' under directory 'abr_jaco2'
> warning: no files found matching '*.dylib' under directory 'abr_jaco2'
> warning: no files found matching '*.msim' under directory 'abr_jaco2'
> warning: no files found matching '*.ttt' under directory 'abr_jaco2'
> writing manifest file 'abr_jaco2.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> running build_py
> running build_ext
> skipping 'abr_jaco2/interface/jaco2_cython.cpp' Cython extension (up-to-date)
> building 'abr_jaco2.interface.jaco2_rs485' extension
> gcc -pthread -B /home/mlcs/anaconda3/envs/py/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/mlcs/anaconda3/envs/py/lib/python3.7/site-packages/numpy/core/include -I/home/mlcs/anaconda3/envs/py/include/python3.7m -I/home/mlcs/anaconda3/envs/py/lib/python3.7/site-packages/numpy/core/include -c abr_jaco2/interface/jaco2_cython.cpp -o build/temp.linux-x86_64-3.7/abr_jaco2/interface/jaco2_cython.o -ldl
> cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
> In file included from /home/mlcs/anaconda3/envs/py/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
>                  from /home/mlcs/anaconda3/envs/py/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
>                  from /home/mlcs/anaconda3/envs/py/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
>                  from abr_jaco2/interface/jaco2_cython.cpp:449:
> /home/mlcs/anaconda3/envs/py/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
>  #warning "Using deprecated NumPy API, disable it with " \
>   ^~~~~~~
> In file included from abr_jaco2/interface/jaco2_cython.cpp:451:0:
> abr_jaco2/interface/jaco2_rs485.h:24:0: warning: "RS485_MSG_GET_ACTUALPOSITION" redefined
>  #define RS485_MSG_GET_ACTUALPOSITION 0x0001
>  
> In file included from abr_jaco2/interface/jaco2_rs485.h:17:0,
>                  from abr_jaco2/interface/jaco2_cython.cpp:451:
> abr_jaco2/interface/kinova-api/Kinova.API.CommLayerUbuntu.h:113:0: note: this is the location of the previous definition
>  #define RS485_MSG_GET_ACTUALPOSITION                      0x01
>  
> abr_jaco2/interface/jaco2_cython.cpp: In function ‘PyObject* __Pyx_PyCFunction_FastCall(PyObject*, PyObject**, Py_ssize_t)’:
> abr_jaco2/interface/jaco2_cython.cpp:6632:69: error: too many arguments to function
>      return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
>                                                                      ^
> abr_jaco2/interface/jaco2_cython.cpp: In function ‘void __Pyx__ExceptionSave(PyThreadState*, PyObject**, PyObject**, PyObject**)’:
> abr_jaco2/interface/jaco2_cython.cpp:6853:21: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
>      *type = tstate->exc_type;
>                      ^~~~~~~~
>                      curexc_type
> abr_jaco2/interface/jaco2_cython.cpp:6854:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
>      *value = tstate->exc_value;
>                       ^~~~~~~~~
>                       curexc_value
> abr_jaco2/interface/jaco2_cython.cpp:6855:19: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
>      *tb = tstate->exc_traceback;
>                    ^~~~~~~~~~~~~
>                    curexc_traceback
> abr_jaco2/interface/jaco2_cython.cpp: In function ‘void __Pyx__ExceptionReset(PyThreadState*, PyObject*, PyObject*, PyObject*)’:
> abr_jaco2/interface/jaco2_cython.cpp:6862:24: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
>      tmp_type = tstate->exc_type;
>                         ^~~~~~~~
>                         curexc_type
> abr_jaco2/interface/jaco2_cython.cpp:6863:25: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
>      tmp_value = tstate->exc_value;
>                          ^~~~~~~~~
>                          curexc_value
> abr_jaco2/interface/jaco2_cython.cpp:6864:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
>      tmp_tb = tstate->exc_traceback;
>                       ^~~~~~~~~~~~~
>                       curexc_traceback
> abr_jaco2/interface/jaco2_cython.cpp:6865:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
>      tstate->exc_type = type;
>              ^~~~~~~~
>              curexc_type
> abr_jaco2/interface/jaco2_cython.cpp:6866:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
>      tstate->exc_value = value;
>              ^~~~~~~~~
>              curexc_value
> abr_jaco2/interface/jaco2_cython.cpp:6867:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
>      tstate->exc_traceback = tb;
>              ^~~~~~~~~~~~~
>              curexc_traceback
> abr_jaco2/interface/jaco2_cython.cpp: In function ‘int __Pyx__GetException(PyThreadState*, PyObject**, PyObject**, PyObject**)’:
> abr_jaco2/interface/jaco2_cython.cpp:6922:24: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
>      tmp_type = tstate->exc_type;
>                         ^~~~~~~~
>                         curexc_type
> abr_jaco2/interface/jaco2_cython.cpp:6923:25: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
>      tmp_value = tstate->exc_value;
>                          ^~~~~~~~~
>                          curexc_value
> abr_jaco2/interface/jaco2_cython.cpp:6924:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
>      tmp_tb = tstate->exc_traceback;
>                       ^~~~~~~~~~~~~
>                       curexc_traceback
> abr_jaco2/interface/jaco2_cython.cpp:6925:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
>      tstate->exc_type = local_type;
>              ^~~~~~~~
>              curexc_type
> abr_jaco2/interface/jaco2_cython.cpp:6926:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
>      tstate->exc_value = local_value;
>              ^~~~~~~~~
>              curexc_value
> abr_jaco2/interface/jaco2_cython.cpp:6927:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
>      tstate->exc_traceback = local_tb;
>              ^~~~~~~~~~~~~
>              curexc_traceback
> error: command 'gcc' failed with exit status 1
>

**Comment by p3jawors** [comment]
Hello taegyuahn,

Thanks for checking out the repo. The timing is actually quite perfect, as I haven't touched this code in over a year, but just looked into testing it out again yesterday. I ran into the same issues and have some temporary fixes until the repo gets updated.

1. Make sure you're using an anaconda enviornment with python=3.5 (`conda create --name env_name python=3.5`)
2. checkout and install the `jaco2` branch of `abr_control` first (`git clone --branch jaco2 https://github.com/abr/abr_control.git`)
3. `pip install requests`
4. when you install the jaco repo, just install it with `pip install -e .`

This fixed things on my end, and I just ran through the setup again to confirm. Let me know how it works out for you.

Cheers,

Pawel

**Comment by taegyuahn** [comment]
Hello p3jawars,

Thank you for answering my issue immediately.

I followed your instructions with python=3.5 and there was no problem while installing jaco repo.

However, I encountered an error as below when I tried to run example script in jaco README.

I think this incompatibility happens because "abr_control" repo needs python=3.7+ (I tried to run by python=3.6 but "abr_control" repo can be installed at least python=3.7) but "abr_jaco2" repo requires python=3.5.

Any help would be appreciated.

Thanks.

taegyu Ahn.


> Traceback (most recent call last): File "example.py", line 8, in <module> import abr_jaco2 File "/home/mlcs/abr_jaco2/abr_jaco2/__init__.py", line 1, in <module> from .config.config import Config File "/home/mlcs/abr_jaco2/abr_jaco2/config/config.py", line 3, in <module> from abr_control.arms.base_config import BaseConfig File "/home/mlcs/abr_control/abr_control/arms/base_config.py", line 8, in <module> import sympy as sp File "/home/mlcs/anaconda3/envs/py35/lib/python3.5/site-packages/sympy-1.7.1-py3.5.egg/sympy/__init__.py", line 17, in <module> raise ImportError("Python version 3.6 or above is required for SymPy.") ImportError: Python version 3.6 or above is required for SymPy.

**Comment by TMmichi** [comment]
@taegyuahn It seems like the error comes from the version incompatibility between sympy-1.7.1 and python 3.5.

Please try with sympy-1.6.2 and see if it works.

Cheers,
tmmichi

**Comment by p3jawors** [comment]
It sounds like you're not on the `jaco2` branch of abr_control. The python 3.7 limit should be fixed in that branch. I just went through the install again with a new environment following the 4 steps above and it works for me.

**Comment by taegyuahn** [comment]
Hello, 
I'm really appreciated for your for your support.

I reinstalled and followed your instructions again and I successfully ran "connection_test.py" file from "example" folder.
I also tried to run "reaching_osc.py" and got some messages which state 
several "joint # calculating..."  on terminal but it seemed to take so much time to have proceeded.
So I ran again but after the first trier, I only got messages which state 

(first time)
"Segmentation fault (core dumped)"
(ctrl+c and run again: second time)
"Using Force Command 0x200: 512
INFO: RS485 initialization completed
INFO: Activating Jaco2..." (I waited more than 20 minutes but there was no further message)

I reinstalled several times following your instructions but there was no difference.
Did I something wrong?

Thank you,
taegyuahn.

**Comment by p3jawors** [comment]
When using the low-level force control, there is a strict initialization phase that needs to be followed, and then the controller expects a control signal at a minimum of every 500ms (although it will perform poorly at this frequency). If either the initialization phase is interupted or the control signal frequency is too slow, it will put the arm into a safety shutoff mode that sets it back to position mode. This is something that cannot be turned off, but I have increased this to it's maximum limit. When this happens you just need to power cycle the arm and give it about 10-20 seconds to reconnect to your computer. Whenever you get a `Segmentation fault (core dumped)` error, the solution will be to power cycle the arm.

For the other problem, when you first use the arm it will need to calculate the various transforms and jacobians. It will save them as sympy functions in `/home/.cache/abr_control/abr_jaco2/<autogenerated_hash>`. This only needs to be done once, as long as the arms config file is not changed. Depending on how powerful your computer is, this may even take several hours. As a point of reference, I just ran through recalculating these, and on an `AMD Ryzen 9 3950x` it takes me about 4 minutes. I also get similar times with an i7-6700K.

I would recommend deleting the folder generated in `/home/.cache/abr_control/abr_jaco2` and running the `control_loop_speed_test.py` example. You'll get a Segmentation fault again because of how long it takes to calculate the transforms, but you'll just need to power cycle, and should be good to go from that point. For your sanity, this is the print out you should get throughout the process, so you can get a rough idea of the progress.

```Generating transform function for EE[0,0,0]_Tx
Generating Jacobian function for EE[0,0,0]_J
Loading expression from EE[0,0,0]_Tx ...
Generating inertia matrix function
Generating Jacobian function for link0[0,0,0]_J
Generating transform function for link0[0,0,0]_Tx
Generating Jacobian function for link1[0,0,0]_J
Generating transform function for link1[0,0,0]_Tx
Generating Jacobian function for link2[0,0,0]_J
Generating transform function for link2[0,0,0]_Tx
Generating Jacobian function for link3[0,0,0]_J
Generating transform function for link3[0,0,0]_Tx
Generating Jacobian function for link4[0,0,0]_J
Generating transform function for link4[0,0,0]_Tx
Generating Jacobian function for link5[0,0,0]_J
Generating transform function for link5[0,0,0]_Tx
Generating Jacobian function for link6[0,0,0]_J
Generating transform function for link6[0,0,0]_Tx
Generating Jacobian function for joint0[0,0,0]_J
Generating transform function for joint0[0,0,0]_Tx
Generating Jacobian function for joint1[0,0,0]_J
Generating transform function for joint1[0,0,0]_Tx
Generating Jacobian function for joint2[0,0,0]_J
Generating transform function for joint2[0,0,0]_Tx
Generating Jacobian function for joint3[0,0,0]_J
Generating transform function for joint3[0,0,0]_Tx
Generating Jacobian function for joint4[0,0,0]_J
Generating transform function for joint4[0,0,0]_Tx
Generating Jacobian function for joint5[0,0,0]_J
Generating transform function for joint5[0,0,0]_Tx
Generating gravity compensation function
Loading expression from link0[0,0,0]_J ...
Loading expression from link1[0,0,0]_J ...
Loading expression from link2[0,0,0]_J ...
Loading expression from link3[0,0,0]_J ...
Loading expression from link4[0,0,0]_J ...
Loading expression from link5[0,0,0]_J ...
Loading expression from link6[0,0,0]_J ...
Loading expression from joint0[0,0,0]_J ...
Loading expression from joint1[0,0,0]_J ...
Loading expression from joint2[0,0,0]_J ...
Loading expression from joint3[0,0,0]_J ...
Loading expression from joint4[0,0,0]_J ...
Loading expression from joint5[0,0,0]_J ...                                           
Using Force Command 0x200: 512
ERROR:  while Initializing
INFO: Connection successful
Segmentation fault (core dumped)```

The same transforms are calculated for this example as for `reaching_osc.py`. They both require all the transforms/jacobians as they are doing OSC. However, you should run the `control_loop_speed_test.py` example first to see if your computer is powerful enough to generate the control signals fast enough for reasonable control. The jaco2 is already fairly limited in its control frequency in force mode. We have only been able to achieve ~350Hz max. This example will just use OSC to maintain the starting position.

Hopefullly this will be the last debugging you'll need to do, but let me know how it goes. Cheers,

Pawel

**Comment by taegyuahn** [comment]
Firstly, thanks for your quick reply. Hoped it was the last debugging on our side as well, but we were out of luck :)

As you suggested, we've deleted the cache file within the abr_jaco2 and re-ran the `control_loop_speed_test.py`, and get the print out as follows:
```
Generating Jacobian function for EE[0,0,0]_J
Generating transform function for EE[0,0,0]_Tx
Generating inertia matrix function
Generating Jacobian function for link0[0,0,0]_J
Generating transform function for link0[0,0,0]_Tx
Generating Jacobian function for link1[0,0,0]_J
Generating transform function for link1[0,0,0]_Tx
Generating Jacobian function for link2[0,0,0]_J
Generating transform function for link2[0,0,0]_Tx
Generating Jacobian function for link3[0,0,0]_J
Generating transform function for link3[0,0,0]_Tx
Generating Jacobian function for link4[0,0,0]_J
Generating transform function for link4[0,0,0]_Tx
Generating Jacobian function for link5[0,0,0]_J
Generating transform function for link5[0,0,0]_Tx
Generating Jacobian function for link6[0,0,0]_J
Generating transform function for link6[0,0,0]_Tx
Generating Jacobian function for joint0[0,0,0]_J
Generating transform function for joint0[0,0,0]_Tx
Generating Jacobian function for joint1[0,0,0]_J
Generating transform function for joint1[0,0,0]_Tx
Generating Jacobian function for joint2[0,0,0]_J
Generating transform function for joint2[0,0,0]_Tx
Generating Jacobian function for joint3[0,0,0]_J
Generating transform function for joint3[0,0,0]_Tx
Generating Jacobian function for joint4[0,0,0]_J
Generating transform function for joint4[0,0,0]_Tx
Generating Jacobian function for joint5[0,0,0]_J
Generating transform function for joint5[0,0,0]_Tx
Loading expression from EE[0,0,0]_Tx ...
Generating gravity compensation function
Loading expression from link0[0,0,0]_J ...
Loading expression from link1[0,0,0]_J ...
Loading expression from link2[0,0,0]_J ...
Loading expression from link3[0,0,0]_J ...
Loading expression from link4[0,0,0]_J ...
Loading expression from link5[0,0,0]_J ...
Loading expression from link6[0,0,0]_J ...
Loading expression from joint0[0,0,0]_J ...
Loading expression from joint1[0,0,0]_J ...
Loading expression from joint2[0,0,0]_J ...
Loading expression from joint3[0,0,0]_J ...
Loading expression from joint4[0,0,0]_J ...
Loading expression from joint5[0,0,0]_J ...
Segmentation fault (core dumped)
```
Although it seems quite similar to the print out of yours, there are some mismatches (order changes of the line `Loading expression from EE[0,0,0]_Tx ...` or no `Using Force command` to `INFO: Connection successful` before `Segmentation fault (core dump)` occurs.

I'm currently on commit: `9eea8ad708613db2dc01ffe560717a033b8848c5` with branch jaco2 of abr_control. Just wondering if that's same as yours.

After the power cycling our arm, we ran `control_loop_speed_test.py` again, and get the print out as follows:
```
Using Force Command 0x200: 512
INFO: RS485 initialization completed
INFO: Activating Jaco2...
```
with no response afterwards. We've done some debugging, and it seems like MYRS485_Write and Read does not function properly, as our updated[ii] buffer still remains same with full of zeros. 

We've checked the usb connection via `dmesg` command to see if our connection between the arm and the computer is stable, and seems like there is no problem with it.

Am I missing something here?
Looking forward to your reply.

Best regards,
taegyuahn

**Comment by p3jawors** [comment]
Have you installed the Kinova SDK? I should have included that in the setup instructions, but you need to install their SDK so that your computer can communicate with the arm. I can't seem to find it on their site, but I've attached the files here. Assuming you are on a 64bit Ubuntu machine, you just need to go to `KINOVA_SDK/Ubuntu/16_04/64\ bits/` and run `./installSDK64.sh`. This will take you through the install process.

Here is the Kinova document for the process https://www.kinovarobotics.com/sites/default/files/SDK-UG-INT-EN%20201804-1.0%20%28KINOVA%E2%84%A2%20Software%20development%20kit%20user%20guide%29_2.pdf

**Comment by taegyuahn** [comment]
I have installed a Kinova SDK file which you have suggested and finally the 'control_loop_speed_test.py' and reaching_osc.py' file worked.

However, when I changed the target_xyz list in the 'reaching_osc.py' file and ran that file, 
the jaco arm moves to the highest position and the control joystick blinks.
(messages of 'control_loop_speed_test.py')
'''
(jaco) mlcs@mlcs:~/Project/abr_jaco2/examples$ python control_loop_speed_test.py 
Using Force Command 0x200: 512
INFO: RS485 initialization completed
INFO: Activating Jaco2...
INFO: Connection successful
INFO: Position control mode activated
Running loop speed test for the next 10 seconds...
During this time the arm will try to maintain its position
'''
(messages of 'reaching_osc.py')
'''
(jaco) mlcs@mlcs:~/Project/abr_jaco2/examples$ python reaching_osc.py 
Using Force Command 0x200: 512
INFO: RS485 initialization completed
INFO: Activating Jaco2...
INFO: Connection successful
INFO: Position control mode activated
Using Force Command 0x200: 512
INFO: RS485 initialization completed
INFO: Activating Jaco2...
INFO: Connection successful
INFO: Position control mode activated
'''

So I ran every files again that I had successfully ran but every time the results were same.(arm goes upward and joystick blinks)
I also reinstalled all the repos and followed your instructions again but nothing changed.
I guess that the arm status becomes a position mode whenever I run those examples.

Am I missing something here?
Looking forward to your reply.

Best regards,
taegyuahn

**Comment by p3jawors** [comment]
I would disconnect the joystick just incase it confuses the onboard processing as to what it should be getting input from. I never keep it connected while using the Jaco so I can't speak as to what it might do. As for the arm going straight up it would depend on what you set you target_xyz to. From the starting position the end-effector is at world cartesian coordinates `[-0.00203117, -0.00516454,  1.18698139]`. I would try to limit the distance you reach to be less than 0.9m away from the second actuator because that is the point where it pivots in xy. You can get the positions of different joints and links by running
`robot_config.Tx('<joint or link name>', interface.feedback['q'])`
In the case I mentioned your joint name would be `joint1`, then just check the distance between that and your target points.

**Comment by TMmichi** [comment]
Sorry for the delayed reply, and thanks for your suggestion.

Although disconnecting the joystick didn't solve our problem, keeping the end-effector close from the joint1 manged to have the force_mode working.

Since we're no longer facing any issues regarding setup.py, I suggest @taegyuahn to close this issue. Thanks again to the author of this package for his fast and informative feedback.
